# Generated by Django 4.1.3 on 2022-12-03 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now=True, verbose_name="작성일자"),
                ),
                ("start", models.DateTimeField(verbose_name="start")),
                ("end", models.DateTimeField(verbose_name="end")),
                ("title", models.CharField(max_length=20, verbose_name="name")),
                ("content", models.TextField(verbose_name="desc")),
                ("allDay", models.BooleanField(default=False)),
                (
                    "cls",
                    models.CharField(
                        choices=[
                            ("P", "Private"),
                            ("S", "Shared"),
                            ("O", "OnGoing"),
                            ("D", "Done"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="참여인원", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "이벤트",
                "verbose_name_plural": "이벤트",
            },
        ),
    ]
