# Generated by Django 4.1.3 on 2022-12-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmeeting",
            name="create_date",
            field=models.DateTimeField(auto_now=True, verbose_name="작성일자"),
        ),
    ]
