# Generated by Django 4.1.3 on 2022-12-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
        ("event", "0002_alter_projectmeeting_create_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Private",
            fields=[
                (
                    "baseevent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="event.baseevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "개인 스케쥴",
                "verbose_name_plural": "개인 스케쥴",
            },
            bases=("event.baseevent",),
        ),
        migrations.RemoveField(
            model_name="baseevent",
            name="cls",
        ),
        migrations.RemoveField(
            model_name="baseevent",
            name="content",
        ),
        migrations.CreateModel(
            name="Public",
            fields=[
                (
                    "baseevent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="event.baseevent",
                    ),
                ),
                ("content", models.TextField(default="", verbose_name="desc")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "프로젝트 미팅",
                "verbose_name_plural": "프로젝트 미팅",
            },
            bases=("event.baseevent",),
        ),
        migrations.DeleteModel(
            name="ProjectMeeting",
        ),
    ]
