# Generated by Django 4.1.3 on 2022-12-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_private_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseevent",
            name="cls",
            field=models.CharField(
                choices=[("Pr", "Private"), ("Pb", "Public")],
                default="Pr",
                max_length=2,
            ),
        ),
    ]
