# Generated by Django 4.1.3 on 2022-12-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_baseevent_cls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseevent",
            name="cls",
            field=models.CharField(
                choices=[("private", "Private"), ("public", "Public")],
                default="private",
                max_length=10,
            ),
        ),
    ]
