# Generated by Django 4.1.3 on 2022-12-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_alter_baseevent_cls"),
    ]

    operations = [
        migrations.AddField(
            model_name="public",
            name="schedules",
            field=models.JSONField(default=[], verbose_name="schedules"),
        ),
    ]
