# Generated by Django 4.1.3 on 2022-12-19 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
        ("event", "0007_public_schedules"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="public",
            name="schedules",
        ),
        migrations.AlterField(
            model_name="baseevent",
            name="cls",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("public", "Public"),
                    ("pBlock", "PublicBlock"),
                ],
                default="private",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="PulbicBlock",
            fields=[
                (
                    "baseevent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="event.baseevent",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="project.song",
                    ),
                ),
            ],
            options={
                "verbose_name": "블록",
                "verbose_name_plural": "블록",
            },
            bases=("event.baseevent",),
        ),
        migrations.AddField(
            model_name="public",
            name="blocks",
            field=models.ManyToManyField(
                related_name="meeting", to="event.pulbicblock"
            ),
        ),
    ]
