# Generated by Django 4.1.3 on 2022-12-03 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=20)),
                ("name", models.CharField(default="unnamed", max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "연주자",
                "verbose_name_plural": "연주자",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now=True, verbose_name="작성일자"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="수정일자"),
                ),
                (
                    "title",
                    models.CharField(max_length=20, unique=True, verbose_name="이름"),
                ),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Prepare"),
                            ("R", "Ready"),
                            ("O", "OnGoing"),
                            ("D", "Done"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "프로젝트",
                "verbose_name_plural": "프로젝트",
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now=True, verbose_name="작성일자"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="수정일자"),
                ),
                ("title", models.CharField(max_length=50, verbose_name="곡명")),
                ("artist", models.CharField(max_length=50, verbose_name="아티스트")),
                ("content", models.TextField(verbose_name="비고")),
                ("instruments", models.JSONField(default=[], verbose_name="positions")),
                ("fix", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="project.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "곡",
                "verbose_name_plural": "곡",
            },
        ),
        migrations.CreateModel(
            name="SongPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fixed", models.BooleanField(default=False)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.player"
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="project.song",
                    ),
                ),
            ],
            options={
                "verbose_name": "곡에 bind된 연주자",
                "verbose_name_plural": "곡에 bind된 연주자",
            },
        ),
    ]
